# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VizTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!


  # Pods for VizTest
  pod 'ImageFilesPicker'
  pod 'AFNetworking', '~> 3.0'


end
